---
title: "Real Estate Price Prediction Using Ordinary Lease Squares Regression (n > p)"
author: "Bedrock Stat Analytics"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: 
  pdf_document:
    fig_caption: yes
  pandoc_args: [
      "--number-sections",
      "--number-offset=1"
    ]

header-includes:
- \usepackage{pdflscape}
- \usepackage{booktabs}
- \usepackage{longtable}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}

params:
  dat_data: NA
  dat_file: NA
---

```{r include=FALSE}
knitr::opts_chunk$set(comment = NA)
```


```{r,echo=FALSE,warning=FALSE,message=FALSE, error=FALSE}
library(caret)
library(knitr)
library(elasticnet)
#library(glmnet) # Package to fit ridge/lasso/elastic net models
library(DMwR)
#library(boot) # Package to do bootstrap error estimates
library(prettyR)
library(xtable)
library(kableExtra)
library(broom)
```

```{r,echo=F}
#dat <- params$dat_data
#name <- params$dat_file
#knitr::kable(dat)
``` 

```{r cache=FALSE, echo=FALSE}
read_chunk('BEDROCK-OLS.R')
read_chunk('BEDROCK-HELP-FUNC.R')
```

```{r, echo=FALSE}
# Load data file
dat <- params$dat_data
#dat <- read.csv(file='20_Obs_LL.csv')
# read chunk (does not run code)
dataIn <- dat
dataIn <- dataIn[ , !names(dataIn) %in% c("MezzanineYes1")]
indx <- sapply(dataIn, is.factor)
dataIn[indx] <- lapply(dataIn[indx], function(x) as.numeric(x))
```


# Summary Statistics
```{r  descriptive_stat, results='asis', echo = FALSE, message=FALSE}
# Sumary of unscaled predictor (x) variables  
```
```{r ols_preprocess, echo=FALSE}
# Pre-process
```

# Correlations Between Predictors
```{r ols_cor_plot, echo=FALSE, fig.height=12,fig.width=12}
# Plot the correlations between predictors
```

# Variable Importance
```{r  make_model, echo = F}
```
```{r var_importance, echo=FALSE,fig.height=10,fig.width=10}
# get varible importance
```
```{r  best_model, echo = FALSE}
```

# Standardized Model Coefficients
```{r  ols_coef, echo = FALSE}
```
```{r  ols_coef_tble, results ='asis', echo = FALSE}
```
# Model Prediction
```{r predict_price, echo = FALSE, results ='asis'}
```


\newpage
# Appendix
\blandscape 
Appendix
```{r, echo=FALSE}
knitr::kable(dat, 
             format = "latex",
             booktabs = TRUE,
             caption = "Raw data table") %>%
kableExtra::kable_styling(latex_options = c("repeat_header"), font_size = 7) 
``` 
\elandscape 
